#define RVLRECOGNITION_MODE_RECOGNITION			0
#define RVLRECOGNITION_MODE_TRAINING			1
#define RVLRECOGNITION_PROBLEM_SHAPE_INSTANCE_DETECTION		0
#define RVLRECOGNITION_PROBLEM_CLASSIFICATION				1

